'use strict';

let textForPastLivePassiveBonus = {
    bonusDcTrasmutation : 'bonus to DC\'s of your Transmutation spells',
    maximumSpellPoint: 'bonus to maximum spell points (SP)',
    bonusIntelligenceSkills: 'bonus to all intelligence based skills',
    bonusUmd: 'bonus to Use Magic Device Skill',
    bonusHitPoints: 'bonus to total hit points (HP)',
    bonusSavesEnchIll: 'bonus to saves vs. enchantments and illusions',
    bonusBardSongUsage: 'bard song usage',
    bonusDcConjuration: 'bonus to DC\'s of your Conjuration spells',
    turnUndeadAttempt: 'Turn Undead attempt(s)',
    turnUndeadHigher: 'you Turn Undead as if you were for that many levels higher',
    bonusSummon: 'your summoned creatures, charmed minions, and hirelings gain to all ability scores bonus',
    bonusSpellPen: 'bonus to spell penetration',
    bonusAttackRoll: 'bonus to attack rolls',
    bonusDcTactical: 'bonus to DC\'s of your tactical feats',
    bonusDamageRolls: 'bonus to damage rolls',
    bonusPositiveHealAmp: 'bonus to positive healing amplification',
    bonusDmgRanged: 'bonus to damage with ranged weapons (not thrown)',
    elementResistance: 'bonus to elemental resistances',
    bonusSavedTrap: 'bonus to saves vs. traps',
    bonusDmgSneak: 'bonus to damage when sneaking',
    bonusAttackSneak: 'bonus to attack when sneaking',
    bonusDcEvocation: 'bonus to DC\'s of your Evocations spells',
    bonusMrr: 'bonus to magical resistance rating (MRR)',
    bonusDcWands: 'bonus to DC\'s of your wands',
    bonusHaggle: 'bonus to Haggle',
    bonusBalance: 'bonus to Balance',
    bonusMoveSilently: 'bonus to Move Silently',
    bonusSpot: 'bonus to Spot',
    bonusSpellcraft: 'bonus to Spellcraft',
    bonusHeal: 'bonus to Heal',
    bonusSearch: 'bonus to Search',
    bonusDiplomacy: 'bonus to Diplomacy',
    bonusIntimidate: 'bonus to Intimidate',
    bonusTumble: 'bonus to Tumble',
    bonusCharisma: 'bonus to Charisma',
    bonusIntelligence: 'bonus to Intelligence',
    bonusWisdom: 'bonus to Wisdom',
    bonusConstitution: 'bonus to Constitution',
    bonusDexterity: 'bonus to Dexterity',
    bonusStrength: 'bonus to Strength',
    bonusRacialActionPoint: 'bonus points to Racial Enhancement Tree',
    bonusFortitudeSave: 'bonus to fortitude save',
    bonusFortification: '% bonus to fortification',
    bonusPrr: 'bonus to physical resistance rating (PRR)',
    bonusWillSave: 'bonus to will save',
    bonusReflexSave: 'bonus points to reflex save',
    bonusDodge: '% bonus to dodge',
    bonusPositiveSpellPower: 'bonus to positive spell power',
    bonusElementAbsorption: '% bonus to Absorption of Acid, Cold, Electric, and Fire damage',
    bonusAcFlat: 'bonus to AC',
    bonusAcPerTen: 'bonus to AC per 10 character levels',
    bonusHpEpicPerTen: 'bonus to HP per 10 character levels',
    bonusRepair: 'bonus to Repair',
    bonusNegativeHealAmp: 'bonus to negative healing amplification',
    bonusNegativeSpellPower: 'bonus to negative spell power',
    bonusLightningSpellPower: 'bonus to lightning spell power',
    bonusSonicSpellPower: 'bonus to sonic spell power',
    bonusDestinyPoint: 'bonus destiny points',
    bonusAllSkills: 'bonus to all skills',
    bonusPoisonSpellPower: 'bonus to poison spell power',
    bonusAcidSpellPower: 'bonus to acid spell power',
    bonusFireSpellPower: 'bonus to fire spell power',
    bonusDmgMelee: 'bonus to damage with melee weapons',
    bonusBreathDc: 'bonus to breath weapon DC',
    bonusListen: 'bonus to Listen',
}