let optionsArray = [
    'Alchemist',
    'Artificer',
    'Barbarian',
    'Bard',
    'Cleric',
    'Druid',
    'Favored Soul',
    'Fighter',
    'Monk',
    'Paladin',
    'Ranger',
    'Rogue',
    'Sorcerer',
    'Warlock',
    'Wizard',
    'Dark Apostate',
    'Stormsinger',
    'Sacred Fist',
    'Blight Caster',
    'Dark Hunter',
    'Acolyte of the Skin',
    'Dragon Lord',
    'Wild Mage',
    'Human',
    'Dwarf',
    'Elf',
    'Halfling',
    'Aasimar',
    'Dragonborn',
    'Drow',
    'Gnome',
    'Half-Elf',
    'Half-Orc',
    'Shifter',
    'Tiefling',
    'Warforged',
    'Tabaxi',
    'Eladrin',
    'Aasimar Scourge',
    'Bladeforged',
    'Deep Gnome',
    'Purple Dragon Knight',
    'Razorclaw Shifter',
    'Tiefling Scoundrel',
    'Shadar-Kai',
    'Morninglord',
    'Tabaxi Trailblazer',
    'Eladrin Chaosmancer',
    'Dragon Disciple',
    'Energy Criticals',
    'Enchant Weapon',
    'Arcane Alacrity',
    'Ancient Knowledge',
    'Eclipse Power',
    'Power Over Life and Death',
    'Brace',
    'Block Energy',
    'Ancient Blessing',
    'Doublestrike',
    'Skill Mastery',
    'Fortification',
    'Ancient Tactics',
    'Trap Damage Absorption',
    'Doubleshot',
    'Fast Healing',
    'Colors of the Queen',
    'Ancient Power'
]